# general
batch_size: 32
optimizer: sgd
patience: 30
architecture: longfilter
in_channels: 1
max_epoch: 200
exp_name: densenet_small_winlen_256
pretrained: true
normalize_spectrums: true 
learning_rate: 0.01
window_len: 256
debug: false
spec_type: librosa_melspec
dev_step_size: 32
size: 10

# Metadata splits
split_rand_state: 42
split_type: shuffled_kfold
n_splits: 10
