# general
batch_size: 32
optimizer: sgd
patience: 100
architecture: simplecnn
in_channels: 1
max_epoch: 200
exp_name: densenet_small_winlen_256
pretrained: true
normalize_spectrums: true 
learning_rate: 0.01
window_len: 256
debug: false
spec_type: librosa_melspec
split_type: rand_shuffle
split_rand_state: 42
dev_step_size: 64
size: 10
